[workspace]
members = [
    "trader",
    "gui",
    "influxdb",
    "trading",
]

[dependencies]
iced = "0.3.0"
rand = "0.8.4"

[dependencies.influxdb]
version = "0.16.0"
features = ["rust-influxdb"]
